sudo: false
cache:
  directories:
    - _vendor
language: go
go:
  - 1.5
before_install:
  - go get github.com/mattn/gom
install:
  - script/bootstrap
  - script/setup-database -env test
script:
  - script/cibuild
