sudo: false
cache:
  directories:
    - _vendor
language: go
go:
  - 1.6
before_install:
  - go get -u github.com/tools/godep # travis has an old version
install:
  - script/bootstrap
  - script/setup-database -env test
script:
  - script/cibuild

branches:
  only:
    - master

env:
  global:
    - DBNAME=gossip
    - DBUSER=travis
