sudo: false
cache:
  directories:
    - _vendor
language: go
go:
  - tip
before_install:
  - go get github.com/mattn/gom
install:
  - script/bootstrap
  - script/goose -env test up
script:
  - script/cibuild
